# HTTP 连接配置 TODO
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30

# 腾讯云账号相关的信息配置 TODO
tencent:
  sms:
    account:
      secret-id: AKIDc3E8l7C0XooY1EqCI6evve6IDrDI7gy0
      secret-key: nKaZHjunVAZiaBWbPxGI2WjfKipgIdiY
      sign_name: 小郎码知答公众号
      sms-sdk-app-id: 1400695365
      template-id: 1445563

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.221.77.104:3306/water?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Root@123

# flyway配置
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1.0.0
    encoding: UTF-8
    locations: classpath:db/migration
